version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: tp_mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: social_network
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  neo4j:
    image: neo4j:latest
    container_name: tp_neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_heap_initial__size: 2G
      NEO4J_dbms_memory_heap_max__size: 6G
      NEO4J_dbms_memory_transaction_total_max: 4G
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

volumes:
  mariadb_data:
  neo4j_data: